[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  GEMINI_API_KEY = "Your Google Generative AI API key"
  GROQ_API_KEY = "Your Groq API key"